development:
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
  bucket: sadhana_development

test:
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']

production:
  access_key_id: ENV['S3_ACCESS_KEY_ID']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
  bucket: sadhana_production