development:
  google:
    consumer_key: 'sadhana.com.ar'
    consumer_secret: 'kdZ1aPkDsgJ5zN2YRb2iApuM'
  yahoo:
    consumer_key: 'dj0yJmk9Ym5qbG1zNWtKaEx0JmQ9WVdrOVMyZzVVV3MxTnpJbWNHbzlOakl3TmpreE5qSS0mcz1jb25zdW1lcnNlY3JldCZ4PTVj'
    consumer_secret: '9dcd7085905e5dcbf26ddc82f600858524d3cdfb'