google:
  key: google_12345
clicky:
  key: clicky_12345
kiss_metrics:
  js_url_key: //doug1izaerwt3.cloudfront.net/kiss_metrics_12345.1.js
adwords:
  'Some Event':
    id: 4444555555
    language: en
    format: 2
    color: ffffff
    label: xxxxxxxxxxxxxxxx
    value: 0
  'Another Event':
    id: 1111333333
    language: en
    format: 2
    color: ffffff
    label: yyyyyyyyyyyyyyyy
    value: 0
chartbeat:
  key: chartbeat_12345
  domain: your.domain.com
comscore:
  key: comscore_12345
optimizely:
  key: optimizely_12345
quantcast:
  key: p-abc123